typography_spectrum: 0.60317
color:
  brandColors:
    - '#f0e9d9'
    - '#ad5910'
    - '#6c0100'
    - '#41664c'
    - '#e6a561'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.55972
analytics:
  google: UA-754-555-68-1
  facebook: null
  twitter: null
name: Christopher B. James
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CHURCH NOW
    url: 'https://thegrid.ai/churchnow/'
    type: external
  - name: TWITTER
    url: 'https://twitter.com/chrisbjames'
    type: external
  - name: JESUS DUST
    url: 'http://www.jesusdust.com/'
    type: external
  - name: ACADEMIA
    url: 'https://dbq.academia.edu/cbjames'
    type: external
favicon: null
title: Christopher B. James
purpose: []
