name: Christopher B. James
favicon: null
layout_spectrum: 0.55972
typography_spectrum: 0.60317
title: chrisbjames.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-754-555-68-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e9d9'
    - '#ad5910'
    - '#6c0100'
    - '#41664c'
    - '#e6a561'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
