name: chrisbjames
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5031728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#b3d2fd'
    - '#358abf'
    - '#204b8e'
    - '#a18179'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
