name: Christopher B. James
favicon: null
layout_spectrum: 0.6255
typography_spectrum: 0.71867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e9d9'
    - '#ad5910'
    - '#6c0100'
    - '#41664c'
    - '#e6a561'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
